#include <tools/filesystem.h>
#include <string>
#include <cstdlib>
#include "root_directory.h" // This is a configuration file generated by CMake.

std::string FileSystem::getPath(const std::string& path)
{
  char const * envRoot = getenv("LOGL_ROOT_PATH");
  char const * givenRoot = (envRoot != nullptr ? envRoot : logl_root);
  std::string root = (givenRoot != nullptr ? givenRoot : "");
  if (root != "")
    return getPathRelativeRoot(root, path);
  else
    return getPathRelativeBinary(path);

}

std::string FileSystem::getPathRelativeRoot(const std::string& root, const std::string& path)
{
  return root + std::string("/") + path;
}

std::string FileSystem::getPathRelativeBinary(const std::string& path)
{
  return "../../../" + path;
}
